### ISSUE TITLE
Generated package does not work.

### ISSUE THREAD

**Issue by bitdisaster** [Microsoft/InsiderDevTour18-Modernize#1]
I followed the instruction to generate the app installer package. However the resulting package does not work and fails with a parsing error. 
![image](https://user-images.githubusercontent.com/5191943/40641171-8ce96c76-62cd-11e8-9d27-53df657e5a4c.png)

**Comment by cbarkerms** [comment]
are you running the package off your local file system, off a share, somewhere else? are you in developer mode (Windows Settings)? does this happen if you run the packager file directly, or just when you run via index.html?

**Comment by bitdisaster** [comment]
I run it off the local file system, Both, the Microsoft.Knowzy.PackagingProject.appinstaller and the index.html have the same error. However, the appxbundle in the Microsoft.Knowzy.PackagingProject_1.0.0.0_Debug_Test subfolder works.

**Comment by cbarkerms** [comment]
I think I reproduced this. In VS when setting your UNC path, please try using the machine name rather than localhost - i.e. in my case it was something like \\MYCOMPUTERNAME\MYAPPUPDATES, not \\LOCALHOST\MYAPPUPDATES. Does that resolve for you?

**Comment by cbarkerms** [comment]
I updated the instructions to reflect this: https://github.com/Microsoft/InsiderDevTour18-Modernize/commit/2007b79ec5792a98eebc187aff14b0da3f06e661

Please re-open the issue if this does not resolve.
