### ISSUE TITLE
Windows Hello demo unclear

### ISSUE THREAD

**Issue by bitdisaster** [Microsoft/InsiderDevTour18-Modernize#2]
The Windows Hello demo is unclear.

**LoginView.xaml**
Replace <Border> Content with Windows Hello UI.
**LoginView.xaml.cs**
Uncommment functions.

1.)	What Windows Hello UI? From where? Is that prepacked control I can reference?
2.)	There are no commented function in the code behind I could uncomment.

**Comment by cbarkerms** [comment]
Thank you for raising - great point. I just added more details - can you review and close if this helps please:

https://github.com/Microsoft/InsiderDevTour18-Modernize/commit/1bc00b1689f8aa1fafc5be9436830458b7809d4d

Chris

**Comment by bitdisaster** [comment]
Thanks for the quick fix!
